const sampleListings = [
  {
    title: "Mountain Retreat",
    description:
      "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: {
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=60",
      filename: "mountain_retreat",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
    category: "Mountains",
    geometry: {
      type: "Point",
      coordinates: [-106.82, 39.1911],
    },
  },
  {
    title: "Urban Studio Apartment",
    description:
      "Compact and convenient studio apartment in a bustling urban neighborhood. Ideal for short stays.",
    image: {
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=60",
      filename: "urban_studio",
    },
    price: 800,
    location: "Chicago",
    country: "United States",
    category: "Iconic cities",
    geometry: {
      type: "Point",
      coordinates: [-87.6298, 41.8781],
    },
  },
  {
    title: "Beachside Bungalow",
    description:
      "Relax in this cozy bungalow right on the beach. Perfect for families and groups.",
    image: {
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
      filename: "beachside_bungalow",
    },
    price: 1800,
    location: "Miami",
    country: "United States",
    category: "Trendings",
    geometry: {
      type: "Point",
      coordinates: [-80.1918, 25.7617],
    },
  },
  {
    title: "Countryside Farmhouse",
    description:
      "Enjoy a rustic stay at this charming farmhouse surrounded by nature and farmland.",
    image: {
      url: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=800&q=60",
      filename: "countryside_farmhouse",
    },
    price: 700,
    location: "Tuscany",
    country: "Italy",
    category: "Farms",
    geometry: {
      type: "Point",
      coordinates: [11.2558, 43.7711],
    },
  },
  {
    title: "Luxury Villa with Pool",
    description:
      "Experience luxury in this spacious villa with a private pool and stunning views.",
    image: {
      url: "https://images.unsplash.com/photo-1501183638714-9b2f7e3d4f99?auto=format&fit=crop&w=800&q=60",
      filename: "luxury_villa",
    },
    price: 5000,
    location: "Santorini",
    country: "Greece",
    category: "Amazing pools",
    geometry: {
      type: "Point",
      coordinates: [25.4615, 36.3932],
    },
  },
  {
    title: "Rustic Cabin in the Woods",
    description:
      "Cozy up in this rustic cabin surrounded by forest, perfect for nature lovers.",
    image: {
      url: "https://images.unsplash.com/photo-1472220625704-91e1462799b2?auto=format&fit=crop&w=800&q=60",
      filename: "rustic_cabin",
    },
    price: 900,
    location: "Vermont",
    country: "United States",
    category: "Camping",
    geometry: {
      type: "Point",
      coordinates: [-72.5778, 44.5588],
    },
  },
  {
    title: "City Penthouse Suite",
    description:
      "Stay in style in this luxurious penthouse suite with panoramic city views.",
    image: {
      url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=60",
      filename: "city_penthouse",
    },
    price: 3500,
    location: "San Francisco",
    country: "United States",
    category: "Iconic cities",
    geometry: {
      type: "Point",
      coordinates: [-122.4194, 37.7749],
    },
  },
  {
    title: "Tropical Island Hut",
    description:
      "Escape to this charming hut on a tropical island, surrounded by crystal clear waters.",
    image: {
      url: "https://images.unsplash.com/photo-1486308510493-cb6f0b6f9cc5?auto=format&fit=crop&w=800&q=60",
      filename: "tropical_hut",
    },
    price: 2200,
    location: "Bora Bora",
    country: "French Polynesia",
    category: "Trendings",
    geometry: {
      type: "Point",
      coordinates: [-151.7415, -16.5004],
    },
  },
  {
    title: "Historic Castle Stay",
    description:
      "Experience royalty by staying in this beautifully restored historic castle.",
    image: {
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60",
      filename: "historic_castle",
    },
    price: 4000,
    location: "Edinburgh",
    country: "Scotland",
    category: "Castles",
    geometry: {
      type: "Point",
      coordinates: [-3.1883, 55.9533],
    },
  },
  {
    title: "Igloo Dome in the Arctic",
    description:
      "Sleep under the stars in a cozy igloo dome located in the heart of the Arctic wilderness.",
    image: {
      url: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=800&q=60",
      filename: "arctic_igloo",
    },
    price: 3200,
    location: "Lapland",
    country: "Finland",
    category: "Domes",
    geometry: {
      type: "Point",
      coordinates: [25.7479, 67.8558],
    },
  },
  //
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin surrounded by nature.",
    image: {
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      filename: "mountain_retreat",
    },
    price: 1200,
    location: "Aspen",
    country: "United States",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [-106.82, 39.1911] },
  },
  {
    title: "Urban Studio Apartment",
    description: "Compact studio in a bustling urban neighborhood, ideal for short stays.",
    image: {
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80",
      filename: "urban_studio",
    },
    price: 850,
    location: "Chicago",
    country: "United States",
    category: "Rooms",
    geometry: { type: "Point", coordinates: [-87.6298, 41.8781] },
  },
  {
    title: "Beachside Bungalow",
    description: "Cozy bungalow right on the beach, perfect for families and groups.",
    image: {
      url: "https://images.unsplash.com/photo-1501183638714-7f3b1571d9a0?auto=format&fit=crop&w=800&q=80",
      filename: "beachside_bungalow",
    },
    price: 1800,
    location: "Miami",
    country: "United States",
    category: "Trendings",
    geometry: { type: "Point", coordinates: [-80.1918, 25.7617] },
  },
  {
    title: "Countryside Farmhouse",
    description: "Rustic farmhouse surrounded by farmland and nature.",
    image: {
      url: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=800&q=80",
      filename: "farmhouse",
    },
    price: 700,
    location: "Tuscany",
    country: "Italy",
    category: "Farms",
    geometry: { type: "Point", coordinates: [11.2558, 43.7711] },
  },
  {
    title: "Luxury Villa with Pool",
    description: "Spacious villa with private pool and stunning views.",
    image: {
      url: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=800&q=80",
      filename: "luxury_villa_pool",
    },
    price: 5200,
    location: "Santorini",
    country: "Greece",
    category: "Amazing pools",
    geometry: { type: "Point", coordinates: [25.4615, 36.3932] },
  },
  {
    title: "Rustic Cabin in the Woods",
    description: "Cozy cabin surrounded by forest, perfect for nature lovers.",
    image: {
      url: "https://images.unsplash.com/photo-1472220625704-91e1462799b2?auto=format&fit=crop&w=800&q=80",
      filename: "rustic_cabin",
    },
    price: 950,
    location: "Vermont",
    country: "United States",
    category: "Camping",
    geometry: { type: "Point", coordinates: [-72.5778, 44.5588] },
  },
  {
    title: "City Penthouse Suite",
    description: "Luxurious penthouse suite with panoramic city views.",
    image: {
      url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80",
      filename: "city_penthouse",
    },
    price: 3500,
    location: "San Francisco",
    country: "United States",
    category: "Iconic cities",
    geometry: { type: "Point", coordinates: [-122.4194, 37.7749] },
  },
  {
    title: "Tropical Island Hut",
    description: "Charming hut on a tropical island, surrounded by crystal clear waters.",
    image: {
      url: "https://images.unsplash.com/photo-1486308510493-cb6f0b6f9cc5?auto=format&fit=crop&w=800&q=80",
      filename: "island_hut",
    },
    price: 2200,
    location: "Bora Bora",
    country: "French Polynesia",
    category: "Trendings",
    geometry: { type: "Point", coordinates: [-151.7415, -16.5004] },
  },
  {
    title: "Historic Castle Stay",
    description: "Stay in a majestic historic castle with antique decor and sprawling grounds.",
    image: {
      url: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=80",
      filename: "castle_stay",
    },
    price: 3000,
    location: "Edinburgh",
    country: "United Kingdom",
    category: "Castles",
    geometry: { type: "Point", coordinates: [-3.1883, 55.9533] },
  },
  {
    title: "Snowy Arctic Igloo",
    description: "Cozy igloo with modern comforts and northern lights views.",
    image: {
      url: "https://images.unsplash.com/photo-1555255707-7c4d8f3a918b?auto=format&fit=crop&w=800&q=80",
      filename: "arctic_igloo",
    },
    price: 2700,
    location: "Lapland",
    country: "Finland",
    category: "Arctic",
    geometry: { type: "Point", coordinates: [26.5802, 66.5039] },
  },
  {
    title: "Modern Dome Home",
    description: "Futuristic dome home with panoramic views of the desert.",
    image: {
      url: "https://images.unsplash.com/photo-1494522358652-6e9b94e161ff?auto=format&fit=crop&w=800&q=80",
      filename: "dome_home",
    },
    price: 1900,
    location: "Sedona",
    country: "United States",
    category: "Domes",
    geometry: { type: "Point", coordinates: [-111.789, 34.8697] },
  },
  {
    title: "Cozy Room in Downtown Loft",
    description: "Affordable cozy room in stylish downtown loft with great city access.",
    image: {
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
      filename: "downtown_loft",
    },
    price: 650,
    location: "New York",
    country: "United States",
    category: "Rooms",
    geometry: { type: "Point", coordinates: [-74.006, 40.7128] },
  },
  {
    title: "Secluded Mountain Cabin",
    description: "Private cabin nestled deep in the mountains for a peaceful retreat.",
    image: {
      url: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=80",
      filename: "mountain_cabin",
    },
    price: 1100,
    location: "Whistler",
    country: "Canada",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [-122.9574, 50.1163] },
  },
  {
    title: "Gorgeous Poolside Villa",
    description: "Luxury villa featuring a large pool, perfect for summer getaways.",
    image: {
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      filename: "poolside_villa",
    },
    price: 4800,
    location: "Ibiza",
    country: "Spain",
    category: "Amazing pools",
    geometry: { type: "Point", coordinates: [1.432, 38.9067] },
  },
  {
    title: "Rustic Farm Stay",
    description: "Experience farm life on this charming rustic farmhouse with animals and fresh air.",
    image: {
      url: "https://images.unsplash.com/photo-1465311443524-66ec99cc9f70?auto=format&fit=crop&w=800&q=80",
      filename: "rustic_farm",
    },
    price: 720,
    location: "Normandy",
    country: "France",
    category: "Farms",
    geometry: { type: "Point", coordinates: [0.1033, 49.4431] },
  },
  {
    title: "Luxury Urban Apartment",
    description: "Stylish apartment with city views and modern amenities.",
    image: {
      url: "https://images.unsplash.com/photo-1494522358652-6e9b94e161ff?auto=format&fit=crop&w=800&q=80",
      filename: "urban_apartment",
    },
    price: 2500,
    location: "Berlin",
    country: "Germany",
    category: "Rooms",
    geometry: { type: "Point", coordinates: [13.405, 52.52] },
  },
  {
    title: "Heritage Haveli Stay",
    description: "Experience royal living in this beautifully restored haveli with traditional decor.",
    image: {
      url: "https://images.unsplash.com/photo-1576671089447-cb0c242a4923?auto=format&fit=crop&w=800&q=80",
      filename: "heritage_haveli",
    },
    price: 1800,
    location: "Jaipur",
    country: "India",
    category: "Castles",
    geometry: { type: "Point", coordinates: [75.7873, 26.9124] },
  },
  {
    title: "Beachfront Villa",
    description: "Luxurious villa right on the shores of the Arabian Sea with a private pool.",
    image: {
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      filename: "beachfront_villa",
    },
    price: 3500,
    location: "Goa",
    country: "India",
    category: "Amazing pools",
    geometry: { type: "Point", coordinates: [74.124, 15.2993] },
  },
  {
    title: "Cozy Room in Bangalore Apartment",
    description: "Modern room in a tech city apartment, close to IT parks and cafes.",
    image: {
      url: "https://images.unsplash.com/photo-1560448070-c651f2d5ed91?auto=format&fit=crop&w=800&q=80",
      filename: "bangalore_room",
    },
    price: 900,
    location: "Bangalore",
    country: "India",
    category: "Rooms",
    geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
  },
  {
    title: "Mountain View Cottage",
    description: "Peaceful cottage with stunning views of the Himalayas.",
    image: {
      url: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=80",
      filename: "mountain_cottage",
    },
    price: 1300,
    location: "Manali",
    country: "India",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [77.1892, 32.2432] },
  },
  {
    title: "Lakeside Farmhouse",
    description: "Charming farmhouse by a lake with organic farming experience.",
    image: {
      url: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=80",
      filename: "lakeside_farmhouse",
    },
    price: 750,
    location: "Udaipur",
    country: "India",
    category: "Farms",
    geometry: { type: "Point", coordinates: [73.7125, 24.5854] },
  },
  {
    title: "Tranquil Dome Stay",
    description: "Eco-friendly dome home nestled in lush greenery.",
    image: {
      url: "https://images.unsplash.com/photo-1494522358652-6e9b94e161ff?auto=format&fit=crop&w=800&q=80",
      filename: "dome_stay_india",
    },
    price: 1100,
    location: "Rishikesh",
    country: "India",
    category: "Domes",
    geometry: { type: "Point", coordinates: [78.2676, 30.0869] },
  },
  {
    title: "Luxury Poolside Bungalow",
    description: "Modern bungalow with private pool and garden.",
    image: {
      url: "https://images.unsplash.com/photo-1501183638714-7f3b1571d9a0?auto=format&fit=crop&w=800&q=80",
      filename: "poolside_bungalow_india",
    },
    price: 3000,
    location: "Pune",
    country: "India",
    category: "Amazing pools",
    geometry: { type: "Point", coordinates: [73.8567, 18.5204] },
  },
  {
    title: "Desert Camping Experience",
    description: "Spend a night in the Thar desert with a traditional camp setup.",
    image: {
      url: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=800&q=80",
      filename: "desert_camping",
    },
    price: 400,
    location: "Jaisalmer",
    country: "India",
    category: "Camping",
    geometry: { type: "Point", coordinates: [70.9153, 26.9157] },
  },
  {
    title: "Historic Fort Stay",
    description: "Stay in a restored fort with all modern comforts.",
    image: {
      url: "https://images.unsplash.com/photo-1533622597524-ae4d5c7e7a0b?auto=format&fit=crop&w=800&q=80",
      filename: "historic_fort",
    },
    price: 2700,
    location: "Hyderabad",
    country: "India",
    category: "Castles",
    geometry: { type: "Point", coordinates: [78.4867, 17.385] },
  },
  {
    title: "Urban Penthouse with City Views",
    description: "Luxurious penthouse in the heart of Mumbai with skyline views.",
    image: {
      url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80",
      filename: "urban_penthouse_india",
    },
    price: 4500,
    location: "Mumbai",
    country: "India",
    category: "Iconic cities",
    geometry: { type: "Point", coordinates: [72.8777, 19.076] },
  },
  {
    title: "Cozy Room near IT Hub",
    description: "Affordable room perfect for professionals in the IT corridor.",
    image: {
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
      filename: "it_room_india",
    },
    price: 700,
    location: "Noida",
    country: "India",
    category: "Rooms",
    geometry: { type: "Point", coordinates: [77.391, 28.5355] },
  },
  {
    title: "Serene Lakeside Camping",
    description: "Pitch your tent beside a calm lake surrounded by hills.",
    image: {
      url: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=800&q=80",
      filename: "lakeside_camping_india",
    },
    price: 350,
    location: "Nainital",
    country: "India",
    category: "Camping",
    geometry: { type: "Point", coordinates: [79.4636, 29.3919] },
  },
  {
    title: "Traditional Kerala Houseboat",
    description: "Cruise the backwaters of Kerala in this beautiful houseboat.",
    image: {
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      filename: "kerala_houseboat",
    },
    price: 2300,
    location: "Alleppey",
    country: "India",
    category: "Trendings",
    geometry: { type: "Point", coordinates: [76.4708, 9.4981] },
  },
  {
    title: "Eco-Friendly Bamboo Dome",
    description: "Unique bamboo dome home located in serene forests.",
    image: {
      url: "https://images.unsplash.com/photo-1494522358652-6e9b94e161ff?auto=format&fit=crop&w=800&q=80",
      filename: "bamboo_dome_india",
    },
    price: 1200,
    location: "Coorg",
    country: "India",
    category: "Domes",
    geometry: { type: "Point", coordinates: [75.8069, 12.3375] },
  },
  {
    title: "Hilltop Cottage",
    description: "Quiet cottage with panoramic views over the hills.",
    image: {
      url: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=80",
      filename: "hilltop_cottage_india",
    },
    price: 1400,
    location: "Ooty",
    country: "India",
    category: "Mountains",
    geometry: { type: "Point", coordinates: [76.695, 11.4064] },
  },
];

module.exports = { data: sampleListings };
